### ISSUE TITLE
composer require nuhel/filament-cropper in Filament V3

### ISSUE THREAD

**Issue by AFSDARIF** [Nuhel/filament-cropper#16]
![image](https://github.com/Nuhel/filament-cropper/assets/10229660/3d170237-d39d-474a-81a3-4f0109a66cab)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nuhel/filament-cropper[dev-main, 1.0.0, ..., 1.1.2] require filament/filament ^2.0 -> found filament/filament[v2.0.0-beta1, ..., 2.x-dev] but it conflicts with your root composer.json require (3.0).
    - Root composer.json requires nuhel/filament-cropper * -> satisfiable by nuhel/filament-cropper[dev-main, 1.0.0, ..., 1.1.2, 9999999-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require nuhel/filament-cropper:*" to figure out if any version is installable, or "composer require nuhel/filament-cropper:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by Polfo** [comment]
Filament V3 has its own image cropper now. Thanks Nuhel, you helped us in V2.
https://filamentphp.com/docs/3.x/forms/fields/file-upload#cropping-and-resizing-images-without-the-editor
