### ISSUE TITLE
Show 2 FileUploads

### ISSUE THREAD

**Issue by davidtim** [Nuhel/filament-cropper#2]
With this one it show this
<img width="606" alt="Screenshot 2022-12-27 at 4 07 43 PM" src="https://user-images.githubusercontent.com/4997933/209643068-14265d78-dcf9-4f2f-8bc1-7a65a15070ac.png">

**Comment by Nuhel** [comment]
> With this one it show this <img alt="Screenshot 2022-12-27 at 4 07 43 PM" width="606" src="https://user-images.githubusercontent.com/4997933/209643068-14265d78-dcf9-4f2f-8bc1-7a65a15070ac.png">

Hello,

Try Updating The package.
