### ISSUE TITLE
Alpine Expression Error: imageCropper is not defined

### ISSUE THREAD

**Issue by sidharthmenon** [Nuhel/filament-cropper#3]
I am getting following error when using this plugin. Not sure what is the problem.

<img width="1247" alt="Screenshot 2022-12-31 at 1 25 46 PM" src="https://user-images.githubusercontent.com/11781046/210129792-fac06fc1-e479-448f-b805-a98307f550d4.png">

**Comment by Nuhel** [comment]
> I am getting following error when using this plugin. Not sure what is the problem.
> 
> <img alt="Screenshot 2022-12-31 at 1 25 46 PM" width="1247" src="https://user-images.githubusercontent.com/11781046/210129792-fac06fc1-e479-448f-b805-a98307f550d4.png">

Hello sorry for the issue. 

Do you have croppie plugin installed? If yes remove it.

I just tried with new project, no issue.

**Comment by Nuhel** [comment]
Hello do you still facing the same issue?
