### ISSUE TITLE
Allowed Filetypes in error message wrong

### ISSUE THREAD

**Issue by krikru95** [Nuhel/filament-cropper#9]
If we create a cropper instance with only jpg and png images allowed and upload a file with a wrong extension, we get an error message with incorrect filetypes.

For example if we configute the cropper with ` ->acceptedFileTypes(['image/png', 'image/jpeg']);` we get following error message: "Erwartet image/png, image/gif oder image/jpeg". 
This is wrong, because we don't allow the upload of gif-Images. 

How can we change the error message?

**Comment by Nuhel** [comment]
Fixed In V-1.1.2
